testing CD

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -57,15 +57,20 @@ jobs:
     # Step 2: Deploy to EC2
     - name: Deploy Docker Containers on EC2
       run: |
-        # Pass the service name explicitly to the EC2 instance
-        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << EOF
-        # Ensure the SERVICE variable is correctly passed and not empty
+        ssh -o StrictHostKeyChecking=no \
+          ubuntu@${{ secrets.EC2_HOST }} \
+          SERVICE=${{ matrix.service }} \
+          'bash -s' << 'EOF'
+        # Verify the SERVICE variable on the remote host
+        echo "Remote SERVICE value: $SERVICE"
+
+          # Check if SERVICE is set
         if [ -z "$SERVICE" ]; then
-         echo "Error: SERVICE variable is not set"
-         exit 1
+          echo "Error: SERVICE variable is not set"
+          exit 1
         fi
 
-         echo "Deploying service: $SERVICE"
+        echo "Deploying service: $SERVICE""
 
         # Pull the latest Docker image
         docker pull tracktwok/smart_hr_system:"$SERVICE"
